### ISSUE TITLE
netlify-cms-backend-fs is incompatible with netlify-cms-app >=2.11.3

### ISSUE THREAD

**Issue by smashercosmo** [ADARTA/netlify-cms-components#19]
Works with 2.11.2, but with 2.11.3 I'm getting
```
backend.js:6 TypeError: e.getIn is not a function
```

**Comment by talves** [comment]
Not sure what is going on with these without a test case. I guess they made a breaking change in the api without bumping it on a major release.

Since it looks like `netlify-cms` will start handling local file-system updates internally, this plugin will more than likely get deprecated. I will leave this open until we know for sure the new solution works.

**Comment by nennogabriel** [comment]
I run yarn upgrade and have the same problem.

**Comment by talves** [comment]
Closing: https://github.com/ADARTA/netlify-cms-components/issues/21#issuecomment-700221094
